
INSERT INTO correspond VALUES ('CATEGORIE_001','commerce responsable');
INSERT INTO correspond VALUES ('CATEGORIE_001','commerces responsables');
INSERT INTO correspond VALUES ('CATEGORIE_001','developpement durable');
INSERT INTO correspond VALUES ('CATEGORIE_001','engagement durable');
INSERT INTO correspond VALUES ('CATEGORIE_001','entreprise responsable');
INSERT INTO correspond VALUES ('CATEGORIE_001','entreprises responsables');
INSERT INTO correspond VALUES ('CATEGORIE_001','responsabilite sociale et environnementale');
INSERT INTO correspond VALUES ('CATEGORIE_001','investissement socialement responsable');
INSERT INTO correspond VALUES ('CATEGORIE_001','investissement social');
INSERT INTO correspond VALUES ('CATEGORIE_001','investissement sociaux');
INSERT INTO correspond VALUES ('CATEGORIE_001','audit social');
INSERT INTO correspond VALUES ('CATEGORIE_001','audit societal');
INSERT INTO correspond VALUES ('CATEGORIE_001','responsabilite societale');
INSERT INTO correspond VALUES ('CATEGORIE_001','bien-etre des salaries');
INSERT INTO correspond VALUES ('CATEGORIE_001','humanitaire');
INSERT INTO correspond VALUES ('CATEGORIE_001','humanitaires');
INSERT INTO correspond VALUES ('CATEGORIE_001','droits humains');
INSERT INTO correspond VALUES ('CATEGORIE_001','associations locales');
INSERT INTO correspond VALUES ('CATEGORIE_001','association locale');
INSERT INTO correspond VALUES ('CATEGORIE_002','environnement');
INSERT INTO correspond VALUES ('CATEGORIE_002','environnemental');
INSERT INTO correspond VALUES ('CATEGORIE_002','environnementaux');
INSERT INTO correspond VALUES ('CATEGORIE_002','environnements');
INSERT INTO correspond VALUES ('CATEGORIE_002','haute qualite environnementale');
INSERT INTO correspond VALUES ('CATEGORIE_002','risque environnemental');
INSERT INTO correspond VALUES ('CATEGORIE_002','risques environnementaux');
INSERT INTO correspond VALUES ('CATEGORIE_002','developpement eco-responsable');
INSERT INTO correspond VALUES ('CATEGORIE_002','ecologie');
INSERT INTO correspond VALUES ('CATEGORIE_002','ecologique');
INSERT INTO correspond VALUES ('CATEGORIE_002','ecologiques');
INSERT INTO correspond VALUES ('CATEGORIE_002','responsabilite ecologique');
INSERT INTO correspond VALUES ('CATEGORIE_002','empreinte ecologique');
INSERT INTO correspond VALUES ('CATEGORIE_003','code de conduite');
INSERT INTO correspond VALUES ('CATEGORIE_003','code ethique');
INSERT INTO correspond VALUES ('CATEGORIE_003','charte ethique');
INSERT INTO correspond VALUES ('CATEGORIE_003','charte RSE');
INSERT INTO correspond VALUES ('CATEGORIE_004','ISO 8001');
INSERT INTO correspond VALUES ('CATEGORIE_004','ISO 26000');
INSERT INTO correspond VALUES ('CATEGORIE_004','ISO 14001');
INSERT INTO correspond VALUES ('CATEGORIE_004','ISO 9001');
INSERT INTO correspond VALUES ('CATEGORIE_004','AFAQ 1000NR');
INSERT INTO correspond VALUES ('CATEGORIE_004','code ethique');
INSERT INTO correspond VALUES ('CATEGORIE_004','EMAS');
INSERT INTO correspond VALUES ('CATEGORIE_004','SA 8000');
INSERT INTO correspond VALUES ('CATEGORIE_004','SD 21000');
INSERT INTO correspond VALUES ('CATEGORIE_005','label BBC');
INSERT INTO correspond VALUES ('CATEGORIE_005','label egalite professionnelle');
INSERT INTO correspond VALUES ('CATEGORIE_005','label responsabilite sociale');
commit;
