

INSERT INTO mot_cle VALUES ('AFAQ 1000NR','AFAQ 1000NR');
INSERT INTO mot_cle VALUES ('association locale','association locale');
INSERT INTO mot_cle VALUES ('associations locales','associations locales');
INSERT INTO mot_cle VALUES ('audit social','audit social');
INSERT INTO mot_cle VALUES ('audit societal','audit societal');
INSERT INTO mot_cle VALUES ('bien-etre des salaries','bien-etre des salaries');
INSERT INTO mot_cle VALUES ('charte ethique','charte ethique');
INSERT INTO mot_cle VALUES ('charte RSE','charte RSE');
INSERT INTO mot_cle VALUES ('code de conduite','code de conduite');
INSERT INTO mot_cle VALUES ('code ethique','code ethique');
INSERT INTO mot_cle VALUES ('commerce equitable','commerce equitable');
INSERT INTO mot_cle VALUES ('commerce responsable','commerce responsable');
INSERT INTO mot_cle VALUES ('commerces responsables','commerces responsables');
INSERT INTO mot_cle VALUES ('developpement durable','developpement durable');
INSERT INTO mot_cle VALUES ('developpement eco-responsable','developpement eco-responsable');
INSERT INTO mot_cle VALUES ('droits humains','droits humains');
INSERT INTO mot_cle VALUES ('ecologie','ecologie');
INSERT INTO mot_cle VALUES ('ecologique','ecologique');
INSERT INTO mot_cle VALUES ('ecologiques','ecologiques');
INSERT INTO mot_cle VALUES ('EMAS','EMAS');
INSERT INTO mot_cle VALUES ('empreinte ecologique','empreinte ecologique');
INSERT INTO mot_cle VALUES ('engagement durable','engagement durable');
INSERT INTO mot_cle VALUES ('entreprise responsable','entreprise responsable');
INSERT INTO mot_cle VALUES ('entreprises responsables','entreprises responsables');
INSERT INTO mot_cle VALUES ('environnement','environnement');
INSERT INTO mot_cle VALUES ('environnemental','environnemental');
INSERT INTO mot_cle VALUES ('environnementaux','environnementaux');
INSERT INTO mot_cle VALUES ('environnements','environnements');
INSERT INTO mot_cle VALUES ('haute qualite environnementale','haute qualite environnementale');
INSERT INTO mot_cle VALUES ('humanitaire','humanitaire');
INSERT INTO mot_cle VALUES ('humanitaires','humanitaires');
INSERT INTO mot_cle VALUES ('investissement social','investissement social');
INSERT INTO mot_cle VALUES ('investissement socialement responsable','investissement socialement responsable');
INSERT INTO mot_cle VALUES ('investissement sociaux','investissement sociaux');
INSERT INTO mot_cle VALUES ('investissements sociaux','investissements sociaux');
INSERT INTO mot_cle VALUES ('ISO 14001','ISO 14001');
INSERT INTO mot_cle VALUES ('ISO 26000','ISO 26000');
INSERT INTO mot_cle VALUES ('ISO 8001','ISO 8001');
INSERT INTO mot_cle VALUES ('ISO 9001','ISO 9001');
INSERT INTO mot_cle VALUES ('label BBC','label BBC');
INSERT INTO mot_cle VALUES ('label diversite','label diversite');
INSERT INTO mot_cle VALUES ('label egalite professionnelle','label egalite professionnelle');
INSERT INTO mot_cle VALUES ('label responsabilite sociale','label responsabilite sociale');
INSERT INTO mot_cle VALUES ('responsabilite ecologique','responsabilite ecologique');
INSERT INTO mot_cle VALUES ('responsabilite sociale et environnementale','responsabilite sociale et environnementale');
INSERT INTO mot_cle VALUES ('responsabilite societale','responsabilite societale');
INSERT INTO mot_cle VALUES ('risque environnemental','risque environnemental');
INSERT INTO mot_cle VALUES ('risques environnementaux','risques environnementaux');
INSERT INTO mot_cle VALUES ('SA 8000','SA 8000');
INSERT INTO mot_cle VALUES ('SD 21000','SD 21000');
INSERT INTO mot_cle VALUES ('﻿null','﻿null');

commit;